Using serviced volume status to locate data pool

diff --git a/pkg/serviced-fstrim b/pkg/serviced-fstrim
--- a/pkg/serviced-fstrim
+++ b/pkg/serviced-fstrim
@@ -17,15 +17,44 @@
 # It discards the blockes unused by the mounted dfs volumes of serviced
 # It should not run more often than necessary.
 # Please refer to the description of fstrim man page.
-which fstrim>/dev/null 2>&1 || { echo "Error:fstrim not found! Please install." >&2; exit 1; }
 
-# capture block devices of the related serviced volumes
-blk_devs=$(lsblk -n -o MOUNTPOINT,TYPE | sort | uniq | grep -E '/opt/serviced/var/volumes/[^/]+\s+dm')
+err_exit()
+{
+   echo "Error: $1!" >&2
+   exit 1
+}
 
-# no need for fstrim if serviced volumes are not on device-mapper
-(( $? == 0 )) ||    { echo "Serviced volumes not on device-mapper" >&2; exit 0;  }
+ok_exit()
+{
+   echo "Info:$1 ..." >&2
+   exit 0
+}
 
-# handle only the mounted serviced volumes
+if [ "$EUID" -ne 0 ]
+then 
+   err_exit "need to run as root"
+fi
+
+# check dependency
+for prog in fstrim serviced
+do
+    which "$prog" >/dev/null 2>&1 || err_exit "$prog not found"
+done
+
+# locate the thinpool
+svc_vol_status=$(serviced volume status)                    || err_exit "serviced not returning volume status"
+echo "$svc_vol_status" | grep -qE "Driver:\s+devicemapper"  || ok_exit  "serviced not running on devicemapper"
+line=($(echo "$svc_vol_status" | grep -E "^PoolName:"))     || err_exit "cannot find pool name"
+pool_name=${line[1]}
+[ -n $pool_name ]  || err_exit "cannot find pool name"
+
+# fstrim only the mounted serviced volumes
+# find the mount points on the thinpool
+blk_devs=$(lsblk -n -o MOUNTPOINT,TYPE "/dev/mapper/$pool_name" | grep -E '/.+\s+dm')
+
+# no need to fstrim if serviced volumes are not on device-mapper
+(( $? == 0 )) || err_exit "No serviced data volumes on device-mapper"
+
 for i in $(echo "$blk_devs" | cut -d ' ' -f 1)
 do
     fstrim -v $i
